name = "FusMatEroYields"
uuid = "cc0975e7-7da7-4057-a477-77a0fed3e7b5"
authors = ["Jerome Guterl <guterlj@fusion.gat.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
